Repository DMU-MoonRabbit/MoonRabbit-Backend, pull requests merged in 2025-06, with the labels that each got.

#38 [feat] 게시글 및 댓글 삭제 수정 추가 및 리팩터링
  src/main/java/com/bigpicture/moonrabbit/domain/answer/controller/AnswerController.java
  src/main/java/com/bigpicture/moonrabbit/domain/answer/dto/AnswerResponseDTO.java
  src/main/java/com/bigpicture/moonrabbit/domain/answer/service/AnswerService.java
  src/main/java/com/bigpicture/moonrabbit/domain/board/controller/BoardController.java
  src/main/java/com/bigpicture/moonrabbit/domain/board/dto/BoardRequestDTO.java
  src/main/java/com/bigpicture/moonrabbit/domain/board/dto/BoardResponseDTO.java
  src/main/java/com/bigpicture/moonrabbit/domain/board/entity/Board.java
  src/main/java/com/bigpicture/moonrabbit/domain/board/repository/BoardRepository.java
  src/main/java/com/bigpicture/moonrabbit/domain/board/service/BoardService.java
  src/main/java/com/bigpicture/moonrabbit/domain/like/entity/Likes.java
  src/main/java/com/bigpicture/moonrabbit/domain/like/repository/LikesRepository.java
  src/main/java/com/bigpicture/moonrabbit/domain/user/controller/UserController.java
  src/main/java/com/bigpicture/moonrabbit/domain/user/dto/UserRequestDTO.java
  src/main/java/com/bigpicture/moonrabbit/domain/user/service/UserService.java
  src/main/java/com/bigpicture/moonrabbit/global/exception/ErrorCode.java
Labels: 📦 chore, ♻️ refactor, 👾 feat

#43 [feat] AI 기능 추가
  build.gradle
  src/main/java/com/bigpicture/moonrabbit/domain/example/aiservice/AssistantConfiguration.java
  src/main/java/com/bigpicture/moonrabbit/domain/example/aiservice/AssistantController.java
  src/main/java/com/bigpicture/moonrabbit/domain/example/aiservice/AssistantTools.java
  src/main/java/com/bigpicture/moonrabbit/domain/example/aiservice/MyChatModelListener.java
  src/main/java/com/bigpicture/moonrabbit/domain/example/aiservice/StreamingAssistant.java
  src/main/java/com/bigpicture/moonrabbit/domain/example/prompt/CareerAssistant.java
  src/main/java/com/bigpicture/moonrabbit/domain/example/prompt/FamilyAssistant.java
  src/main/java/com/bigpicture/moonrabbit/domain/example/prompt/LoveAssistant.java
  src/main/java/com/bigpicture/moonrabbit/domain/example/prompt/MentalAssistant.java
  src/main/java/com/bigpicture/moonrabbit/domain/example/prompt/PersonalAssistant.java
  src/main/java/com/bigpicture/moonrabbit/domain/example/prompt/SocietyAssistant.java
  src/main/java/com/bigpicture/moonrabbit/global/config/SecurityConfig.java
  src/main/resources/application.properties
Labels: 🐟 승회, 👾 feat

#47 [refactor] 댓글 작성 및 조회 로직 수정
  src/main/java/com/bigpicture/moonrabbit/domain/answer/controller/AnswerController.java
  src/main/java/com/bigpicture/moonrabbit/domain/answer/dto/AnswerRequestDTO.java
  src/main/java/com/bigpicture/moonrabbit/domain/answer/dto/AnswerResponseDTO.java
  src/main/java/com/bigpicture/moonrabbit/domain/answer/entity/Answer.java
  src/main/java/com/bigpicture/moonrabbit/domain/answer/repository/AnswerRepository.java
  src/main/java/com/bigpicture/moonrabbit/domain/answer/service/AnswerService.java
  src/main/java/com/bigpicture/moonrabbit/domain/user/entity/User.java
Labels: 🐛 fix, ♻️ refactor, 😺 도현

#51 [refactor] 유저 조회 정보 수정
  src/main/java/com/bigpicture/moonrabbit/domain/user/dto/UserResponseDTO.java
Labels: ♻️ refactor, 😺 도현
