Repository DMU-MoonRabbit/MoonRabbit-Backend, pull requests merged in 2025-04, with the labels that each got.

#19 [feat] 플레이리스트 기능 추가
  src/main/java/com/bigpicture/moonrabbit/domain/playlist/controller/PlaylistController.java
  src/main/java/com/bigpicture/moonrabbit/domain/playlist/dto/PlaylistRequestDto.java
  src/main/java/com/bigpicture/moonrabbit/domain/playlist/entity/Playlist.java
  src/main/java/com/bigpicture/moonrabbit/domain/playlist/repository/PlaylistRepository.java
  src/main/java/com/bigpicture/moonrabbit/domain/playlist/service/PlaylistService.java
Labels: 🐟 승회, 👾 feat

#21 [build] swagger 의존성 추가
  build.gradle
  src/main/java/com/bigpicture/moonrabbit/global/swagger/SwaggerConfig.java
Labels: ⚙️ setting, 😺 도현

#25 [feat] 구글 회원가입 구현
  build.gradle
  src/main/java/com/bigpicture/moonrabbit/domain/user/controller/UserController.java
  src/main/java/com/bigpicture/moonrabbit/domain/user/entity/User.java
  src/main/java/com/bigpicture/moonrabbit/global/auth/jwt/provider/JwtProvider.java
  src/main/java/com/bigpicture/moonrabbit/global/auth/oauth2/CustomOAuth2User.java
  src/main/java/com/bigpicture/moonrabbit/global/auth/oauth2/CustomOAuth2UserService.java
  src/main/java/com/bigpicture/moonrabbit/global/auth/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/bigpicture/moonrabbit/global/config/SecurityConfig.java
  src/main/resources/application.properties
Labels: 🐭 동민, 👾 feat

#30 [cicd] dockerfile 설정
  .gitignore
  Dockerfile
  docker-compose.yml
Labels: ⚙️ setting, 😺 도현
